version: '3'

services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development

volumes:
  bundle_cache:
